#!/usr/bin/env python3

import argparse
import re
import os

header = "// This file is generated by bake.py\n\nconst unsigned char %s[] = {\n"
footer = "\t0x00,\n};\n\n"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
            prog="bake.py",
            description="Bake file contents to C string",
            epilog="Report bugs to <jox969@gmail.com>.",
    )
    parser.add_argument("input", help="input file")
    parser.add_argument("-o", "--output", help="output file", required=True)
    parser.add_argument("-n", "--name", help="string name", required=False)
    args = parser.parse_args()

    if not args.name:
        args.name = "_binary_"
        args.name += re.sub("[^a-zA-Z0-9]", "_", os.path.basename(args.input))
        args.name += "_start"

    with open(args.output, "w") as output:
        output.write(header % args.name)
        with open(args.input, "rb") as input:
            chars = input.read(16)
            while chars:
                output.write("\t")
                for char in chars:
                    output.write("0x%02x, " % char)
                output.write("\n")
                chars = input.read(16)

        output.write(footer)
