#!/bin/sh
# WIP
# Copyright (c) 2021 Jovan Lanik

# Bake file contents into an object

set -e
error() { echo "$0: $1." >&2; exit 1; }
[ "$#" -ne 2 ] && error "Bad usage"

TEMP=$(mktemp -d)
FILE=$(basename "$1")
INPUT=$(realpath "$1")
OUTPUT=$(realpath "$2")
cd "$TEMP"
{ cat "$INPUT"; printf '\0'; } > "$FILE"
ld -r -b binary -z noexecstack "$FILE" -o "$OUTPUT"
