# Dungeon
# Copyright (c) 2021 Jovan Lanik

# Dungeon Config

game:
{
	fov = 70.0;
	iod = 0.25;
	focus = 50.0;
};

video:
{
	fullscreen = true;
	width = 0;
	height = 0;
	vsync = true;
};

graphics:
{
	msaa = 4;
};

